version: '3'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    #volumes allow to store in a persistent disk the content in a local disk
    #db_data is a volume created by docker directly
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - mynet
    restart: always
    
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpressprod  
    volumes:
      - wordpress_data:/var/www/wordpress
    env_file:
      - .env
    ports:
      - "9000:9000"
    networks:
      - mynet
    depends_on:
      - mariadb
    restart: always

  nginx:
    container_name: nginx
    image: nginxprod
    build: ./requirements/nginx2
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/wordpress
      - ./requirements/nginx2/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress
    restart: always
    networks:
      - mynet
  

networks:
  mynet:
    driver: bridge

volumes:
  wordpress_data:
  mariadb_data:
